### ISSUE TITLE
[Actividad 1] Api keys

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2113-2021-2/Recursos#1]
Hola, dado que esto se probará siempre en local, es válido trabajar las api keys en el código mismo?

**Comment by arpincheira** [comment]
Hola, en casos como esos te recomiendo fuertemente la creación de un archivo en el cual vayas guardando variables de ese estilo. Esto con el objetivo de que el equipo docente pueda cambiar eventualmente dichos valores en el caso de ser necesario.
