### ISSUE TITLE
[Actividad 2] Dudas generales

### ISSUE THREAD

**Issue by agustin-rios** [IIC2113-2021-2/Recursos#7]
Hola, leyendo el enunciado me surgieron las siguientes dudas:

-  En pedidos.json, podemos eliminar la tilde en Proteina? y agregar en ingredientes.json los ingredientes tipo masa?

-  Se puede suponer que solo serán estos tipos de ingredientes { "Masas", "Salsa", "Verdura", "Proteína" } los que pida el programa?

-  En el momento de elegir ingredientes para el platillo, tambien hay que decir si es pizza u otro tipo de masa? o hay que hacer match de ingredientes con los pedidos de cada ayudante? y de ese match de ingredientes decir la comida?

**Comment by arpincheira** [comment]
Hola, las respuestas son las siguientes:
- Sí, pueden quitar la tilde, incluso subiremos nuevas versiones de los archivos sin dicha tilde. Con respecto a añadir masa, eso no lo pueden hacer y no lo recomiendo pues los ayudantes utilizaremos otros archivos de ingredientes para poder corregir el programa y no nos haremos responsables si su programa se cae debido a que no están los ingredientes de tipo masa en nuestros archivos. Ahora, lo que recomiendo es no pensar en las masas como ingredientes sino que como platillos en si mismos o bases las cuales pueden asumir como conocidas a partir del enunciado/los menus dados.

- Efectivamente pueden asumir eso pero deben realizar su actividad de forma tal que sea relativamente sencillo poder admitir nuevos tipos de ingredientes(en caso de ser necesario).

- Yo diría que lo primero, es decir, se debería poder elegir el tipo de platillo al que corresponde dicha receta y según eso guardarlo en alguno de los formatos entregados por el enunciado.

**Comment by vicerc** [comment]
Hola, yo tengo un par de preguntas sobre el segundo menú. 

- Se supone que en algún momento el usuario debería ser capaz de seleccionar alguno de los platos que se encuentran en pedidos.json? En caso de poder seleccionar un platillo, ¿las opciones de ingredientes deberían moverse según cuántos platos tenga el ayudante (en el enunciado las masas partirían en el número 3 por ejemplo)? 
- Tampoco me queda claro si el usuario debe seleccionar en primer lugar la masa y luego los ingredientes, ya que como dices es la base del platillo y no tendría sentido agregar ingredientes sin tener la base. De hecho en el ejemplo del enunciado creo que el usuario no seleccionó ninguna base.
- También me gustaría saber qué tanto podemos modificar los menús según nuestro criterio.

**Comment by arpincheira** [comment]
Hola, estábamos viendo que para poder simplificar aquello que propones realizaremos el siguiente cambio:

El orden del menú de selección va a ser 
Platillos ayudante elegido
Ingredientes(en orden Salsas->Verdura->Proteina)
Mensaje de apoyo para el usuario

Luego, el usuario puede seleccionar si agrega un ingrediente, deshace una de las acciones realizadas, vuelve al menú anterior, sale de la aplicación o cocina.

Posteriormente, en el caso de decidir si cocinar, se le debe preguntar el platillo a cocinar y de este último sacar la base.

Update: Listo el enunciado con el cambio indicado

Con respecto a la última pregunta, no entendí muy bien a que te refieres con modificar los menús.

**Comment by vicerc** [comment]
Gracias por los cambios! Me queda claro, sobre la última pregunta me refería a si podíamos tomarnos algunas libertades como que el usuario además de seleccionar alguno de los platos que ya posee pueda crear uno nuevo.

**Comment by agustin-rios** [comment]
Respecto a lo que dices de los platos, estos tienen que ser descritos en el codigo en ese caso?, es decir el tipo de masa que usan.

**Comment by agustin-rios** [comment]
Nos podrian pasar los recordatorios y recetas que deben ir en los formatos de cada plato?

**Comment by arpincheira** [comment]
> Gracias por los cambios! Me queda claro, sobre la última pregunta me refería a si podíamos tomarnos algunas libertades como que el usuario además de seleccionar alguno de los platos que ya posee pueda crear uno nuevo.

Em... eso como tal no se solicita en el enunciado por lo que no es necesario, de todas formas puedes permitir esa opción y añadirlo como consideración en el readme

**Comment by arpincheira** [comment]
> Respecto a lo que dices de los platos, estos tienen que ser descritos en el codigo en ese caso?, es decir el tipo de masa que usan.

No puedo contestar eso.
