### ISSUE TITLE
[Actividad 2] Flujo programa

### ISSUE THREAD

**Issue by imant1** [IIC2113-2021-2/Recursos#8]
Hola! Varias dudas que a mi juicio van en la misma issue:

1. Cuando seleccionamos un ayudante, se debería desplegar una lista como la siguiente.
  ![image](https://user-images.githubusercontent.com/64439029/138968829-182593e9-3b43-41ba-a749-11106fac0219.png)
  Lo que no me queda claro es si para pasar al siguiente menú **¿se debe seleccionar uno de los platillos del ayudante ya seleccionado?** (en este caso solo 1 o 2 serían inputs válidos)

2. Si la respuesta es afirmativa, entonces si elegimos el primer platillo de Pinchos, **¿el siguiente menú debería verse así?** (El plato fue actualizado)
![image](https://user-images.githubusercontent.com/64439029/138969095-ed3e6e39-ab9c-4d06-a025-ba4a45b8bbec.png)

3. Siguiendo esta misma línea, en el enunciado dice _"Cuando se seleccione la opción cocinar se debe preguntar a cual de los platillos corresponde la receta"_. ¿A qué receta se refiere? ¿No se supone que estábamos agregando o deshaciendo ingredientes del platillo que ya fue seleccionado? (En este caso sería el primer platillo de Pinchos)

En conclusión, había entendido que el flujo del programa es el siguiente:

1. Se selecciona un ayudante
2. Se selecciona uno de los platillos del ayudante seleccionado
3. Se agregan o quitan ingredientes al platillo seleccionado o se cocina el platillo con los posibles cambios realizados
Si mi interpretación del flujo del programa no es la correcta agradecería que me lo indicaran.

Gracias!

**Comment by arpincheira** [comment]
Las respuestas son las siguientes:
1._ Los platillos se seleccionan al momento de cocinar, lo que muestras en la imagen debe aparecer de forma constante en el menú posterior a la selección del mismo.
2._ La respuesta es negativa, así que no aplica
3._ Creo que hay un problema al momento de entender el enunciado pues la idea es crear el platillo en base a lo solicitado, no partir del platillo y modificarlo como das a entender en tu pregunta.

**Comment by imant1** [comment]
Ok perfecto. 
¿Entonces el _Alimento_ (Pizza, Calzone, ...) de la receta se obtiene a partir del platillo que se selecciona una vez se quiere cocinar la receta? 
Por que según el enunciado, al momento de elegir un Ingrediente no se da la opción de elegir la masa/Alimento.
