### ISSUE TITLE
[Actividad 2] Agregar Ingredientes

### ISSUE THREAD

**Issue by imant1** [IIC2113-2021-2/Recursos#9]
Hola!
¿A un platillo se le pueden agregar múltiples ingredientes de un mismo tipo? Por ejemplo, 
![image](https://user-images.githubusercontent.com/64439029/138970190-aec55a9a-b5b2-4af0-be4e-d601a648a86f.png)
¿le puedo agregar camarones, tomate y salsa de cuatro quesos al segundo platillo de Pinchos? ¿O la idea es que cada platillo tenga a lo más un ingrediente de cada tipo?

**Comment by arpincheira** [comment]
Hola, lo que mencionas en la primera pregunta efectivamente puede llegar a pasar, aunque en los menú entregados esto no se muestre como tal.
